# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 476be7ee0999ec414b881090e52285bc29cae77fd59c5c5bc7c2301dff27a83c382ff9058a7e8842454e3996a80257049bda6a4800797b2661c3767549f0982a

test:
  secret_key_base: 4ed95115901f51341d28352b65b26c895aa4360bd600653b8f4196a730277d212af014a33decd5c0b05edee6dd6b96a8a96c44ca7ede01c714997afddb776d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
